name: news_email_reader
description: A geek-oriented news email reader app with AI summarization.
publish_to: 'none'
version: 0.4.5+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  # sqflite: ^2.3.0  # removed: use StorageService(JSON) instead
  # sqflite_common_ffi: ^2.3.0  # removed
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2

  
  # Network & HTTP
  dio: ^5.4.0
  http: ^1.1.2
  
  # Email Protocols
  enough_mail: ^2.1.5
  
  # HTML & Content Rendering
  html: ^0.15.4
  
  # Image Handling
  cached_network_image: ^3.3.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.11.1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  path: ^1.8.3
  file_picker: ^8.0.0+1
  
  # Encryption
  crypto: ^3.0.3
  
  # Logging
  logging: ^1.2.0

  # Platform-specific WebViews
  webview_flutter: ^4.7.0
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
